version: '3.9'

services:
  postgres:
    image: postgres:16.1
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: creator_corner
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
